-- =============================================================================
-- 0017_workspace_chat — the signed-in user's own chat threads
--
-- Run as: moka_migrator
--
-- WHY NOT REUSE chat_conversations
--
-- 0007 already has a conversation table, and it is the wrong one. Every row in
-- `chat_conversations` requires a `chatbot_id`, a `deployment_id` and a
-- `visitor_token_hash`, because it models a STRANGER talking to a published
-- bot on a customer's website. Those rows feed the staff handoff inbox and the
-- public widget's resume path.
--
-- A signed-in member chatting in the workspace has no chatbot, no deployment
-- and no visitor token. Storing them there would have meant inventing all
-- three per thread — and every invented row would have appeared in the inbox
-- as a stranger waiting for a human. Two different things that happen to both
-- be called "chat" get two tables.
--
-- WHOSE THREAD IS IT
--
-- `user_id` is NOT NULL and the API filters on it for every read and write.
-- Say plainly what that is and is not: RLS below gives TENANT isolation, so no
-- organization can reach another's threads under any query. It does NOT give
-- per-user isolation, because `Database.withTenant()` binds only the
-- organization — `current_user_id()` is deliberately NULL inside a
-- tenant-scoped transaction (see 0002), and widening that to bind the user as
-- well would change a primitive the whole system's isolation tests rest on.
--
-- So per-user scoping is a query-layer property here, enforced in
-- WorkspaceChatService and nowhere else. It is written in one place for that
-- reason. Someone with direct SQL access to the tenant can read the rows; that
-- is already true of every table in this database.
-- =============================================================================

CREATE TABLE workspace_threads (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
  -- A thread belongs to a person, not to an API key. Cascade because a thread
  -- whose author is gone belongs to nobody and is nobody's to read.
  user_id         uuid        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  project_id      uuid        REFERENCES projects (id) ON DELETE SET NULL,

  /*
   * Taken from the first thing the user said, trimmed. Not generated by a
   * model: a title is worth one line of code, not a second billable call on
   * every new thread — and a summary of a question you just typed is not
   * information you needed.
   */
  title           text        NOT NULL,
  /** The model the user pinned, or NULL to let the router choose each turn. */
  model_id        text,

  message_count   integer     NOT NULL DEFAULT 0,

  created_at      timestamptz NOT NULL DEFAULT now(),
  last_message_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT workspace_threads_title_present CHECK (length(btrim(title)) > 0)
);

-- The list query: this user's threads, newest activity first.
CREATE INDEX workspace_threads_user_activity_idx
  ON workspace_threads (organization_id, user_id, last_message_at DESC);

-- =============================================================================
-- workspace_thread_messages — the transcript
-- =============================================================================

CREATE TABLE workspace_thread_messages (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
  thread_id       uuid        NOT NULL REFERENCES workspace_threads (id) ON DELETE CASCADE,

  role            text        NOT NULL,
  content         text        NOT NULL,

  /*
   * Which model actually answered, recorded per message rather than per
   * thread. The router may fall back mid-thread, and "which model said this"
   * is the first question asked about an answer somebody disputes.
   */
  model_id        text,
  input_tokens    integer     NOT NULL DEFAULT 0,
  output_tokens   integer     NOT NULL DEFAULT 0,
  /*
   * Set when the turn failed. A failed turn is still written, so a thread that
   * broke shows where it broke instead of silently losing the question that
   * caused it.
   */
  error_code      text,

  created_at      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT workspace_thread_messages_role_valid CHECK (role IN ('user', 'assistant')),
  -- An assistant message may be empty only when it failed; a user message
  -- never may. An empty turn with no error is a bug, not a transcript.
  CONSTRAINT workspace_thread_messages_content_present CHECK (
    length(btrim(content)) > 0 OR (role = 'assistant' AND error_code IS NOT NULL)
  )
);

CREATE INDEX workspace_thread_messages_thread_idx
  ON workspace_thread_messages (organization_id, thread_id, created_at);

-- =============================================================================
-- ROW-LEVEL SECURITY
-- =============================================================================

ALTER TABLE workspace_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspace_threads FORCE  ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON workspace_threads
  USING (organization_id = current_org_id()) WITH CHECK (organization_id = current_org_id());

ALTER TABLE workspace_thread_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspace_thread_messages FORCE  ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON workspace_thread_messages
  USING (organization_id = current_org_id()) WITH CHECK (organization_id = current_org_id());

-- =============================================================================
-- TENANT INTEGRITY
--
-- Composite keys, for the reason established in 0010: referential integrity
-- checks run with row security DISABLED, so a single-column reference is
-- satisfied by any row in the installation. Carrying organization_id into the
-- key makes same-tenancy a referential constraint rather than a policy.
-- =============================================================================

ALTER TABLE workspace_threads ADD CONSTRAINT workspace_threads_org_id_unique
  UNIQUE (organization_id, id);

ALTER TABLE workspace_thread_messages DROP CONSTRAINT workspace_thread_messages_thread_id_fkey;
ALTER TABLE workspace_thread_messages ADD CONSTRAINT workspace_thread_messages_thread_same_org
  FOREIGN KEY (organization_id, thread_id) REFERENCES workspace_threads (organization_id, id)
  ON DELETE CASCADE;

-- =============================================================================
-- GRANTS
--
-- No UPDATE on messages. A transcript is a record of what was said; editing a
-- past turn in place would make the thread disagree with the usage ledger and
-- with whatever the user remembers reading. Deleting a thread removes its
-- messages by cascade, which is the one erasure a person does need.
-- =============================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON workspace_threads TO moka_app;
GRANT SELECT, INSERT, DELETE ON workspace_thread_messages TO moka_app;
